export const actionTypes = {
  REQUEST_GAME: 'REQUEST_GAME',
  REQUEST_NEXT_GAME: 'REQUEST_NEXT_GAME',
  SEND_NEXT_MOVE: 'SEND_NEXT_MOVE',
  RESET_MOVE_LIST: 'RESET_MOVE_LIST',
  PUSH_MOVE_TO_LIST: 'PUSH_MOVE_TO_LIST',
  REQUEST_SCORE: 'REQUEST_SCORE',
  RESET_SCORE: 'RESET_SCORE',
  RESET_GAME: 'RESET_GAME',
  SERVER_OK: 'SERVER_OK',
  SERVER_FAILURE: 'SERVER_FAILURE',
};
